[project]
dependencies = [
    "matplotlib>=3.7.0",
    "numpy>=2.3.0",
    "pyright>=1.1.402",
    "ruff",
    "soundfile>=0.13.1",
    "torch>=2.7.1",
    "torchaudio>=2.7.1",
    "tqdm>=4.67.1",
]
name = "audioloop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"

[project.optional-dependencies]
test = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
    "pytest-mock>=3.10",
]


[tool.ruff]
line-length = 100

[tool.ruff.lint]
# extend-select = ["I", "B", "SIM", "RET"]
extend-select = ["I", "B", "SIM", "RET", "UP", "C4", "F", "RUF", "TID", "E"]
ignore = ["RET504", "E501"]

[tool.ruff.lint.per-file-ignores]
"audioloop/label_audio.py" = ["RET508"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v --tb=short"
