#!/usr/bin/env python3
"""
Production audio labeling tool for human-in-the-loop workflows.

This tool is designed for manual labeling of candidate audio files in production
workflows where no ground truth is available. It works with labeling_candidates
CSV files generated by the active learning pipeline.

Supports both UrbanSound8K and FSD50K datasets with automatic dataset detection
or explicit dataset specification.

For evaluation workflows with ground truth data, use audioloop.auto_label_candidates
or audioloop.utils.auto_labeling instead.

Requirements:
- Candidates CSV must have a 'filepath' column (from active_learning.py output)
- Audio files must be in proper dataset structure
- Use --audio-dir to point to the appropriate audio directory

Usage:
  # Auto-detect dataset from filepath
  python -m audioloop.label_audio outputs/labeling_candidates_v1.csv

  # Explicitly specify UrbanSound8K
  python -m audioloop.label_audio outputs/labeling_candidates_v1.csv --dataset urbansound8k --audio-dir data/urbansound8k

  # Explicitly specify FSD50K
  python -m audioloop.label_audio outputs/labeling_candidates_v1.csv --dataset fsd50k --audio-dir data/FSD50K/FSD50K.dev_audio

Controls:
- 1 or y: Label as POSITIVE (target sound detected)
- 0 or n: Label as NEGATIVE (target sound NOT detected)
- p: Play/replay audio
- x: Stop currently playing audio
- u: Jump to next unlabeled sample
- q: Quit and save

The tool automatically plays audio after each label for efficient workflow.
"""

import argparse
import csv
import os
import subprocess
import sys

from .config import AudioLoopConfig


class SimpleAudioLabeler:
    """Simple terminal-based audio labeling interface with multi-dataset support."""

    def __init__(self, candidates_csv, dataset_name, audio_dir=None):
        """
        Initialize the audio labeler.

        Args:
            candidates_csv: Path to candidates CSV file
            dataset_name: Dataset name ('urbansound8k' or 'fsd50k')
            audio_dir: Directory containing audio files
        """
        self.candidates_csv = candidates_csv
        self.dataset_name = dataset_name
        self.current_index = 0
        self.candidates = []
        self.fieldnames = []
        self.changes_made = False
        self.audio_process = None  # For tracking currently playing audio

        # Load candidates
        self._load_candidates()

        # Set up dataset processor and config
        dataset_kwargs = {}
        if audio_dir:
            dataset_kwargs["audio_root"] = audio_dir

        config = AudioLoopConfig.from_project(dataset=self.dataset_name)
        self.dataset_config = config.get_dataset_config()

        # Set default audio directory if not provided
        if audio_dir is None:
            self.audio_dir = str(self.dataset_config.audio_root)
        else:
            self.audio_dir = audio_dir

        print(f"Using dataset: {self.dataset_name}")
        print(f"Audio directory: {self.audio_dir}")

    def _load_candidates(self):
        """Load candidates from CSV file."""
        with open(self.candidates_csv) as f:
            reader = csv.DictReader(f)
            self.candidates = list(reader)
            self.fieldnames = reader.fieldnames

        print(f"\nLoaded {len(self.candidates)} candidates for labeling")

        # Find already labeled samples
        labeled_count = sum(
            1 for c in self.candidates if c.get("needs_human_label", "").strip() != ""
        )
        if labeled_count > 0:
            print(f"{labeled_count} samples already labeled")

            # Find first unlabeled sample
            for i, candidate in enumerate(self.candidates):
                if candidate.get("needs_human_label", "").strip() == "":
                    self.current_index = i
                    break

    def _get_audio_path(self, candidate):
        """Get the full path to the audio file using dataset config."""
        # First, check if audio_path is directly available (preferred)
        audio_path = candidate.get("audio_path")
        if audio_path and audio_path != "None":
            from pathlib import Path

            path = Path(audio_path)
            if path.exists():
                return str(path)
            # Try relative to audio_dir
            if self.audio_dir:
                alt_path = Path(self.audio_dir) / path.name
                if alt_path.exists():
                    return str(alt_path)

        # Fall back to reconstructing path from filename + fold/split
        filename = candidate.get("filename", "")
        if not filename:
            print(
                "ERROR: No 'filename' column found in candidate. This tool requires candidates from active learning workflow."
            )
            print(f"Candidate columns: {list(candidate.keys())}")
            return None

        # Convert spectrogram filename (.pt) to audio filename
        if filename.endswith(".pt"):
            filename = filename.replace(".pt", self.dataset_config.audio_extension)

        # Extract metadata for dataset-specific path resolution
        fold = candidate.get("fold")  # For UrbanSound8K
        split = candidate.get("split")  # For FSD50K/AudioSet

        # Use dataset config to get audio path
        try:
            audio_path = self.dataset_config.get_audio_path(
                filename=filename, split=split, fold=int(fold) if fold and fold != "-1" else None
            )
            return str(audio_path)

        except Exception as e:
            print(f"ERROR: Failed to get audio path for {filename}: {e}")
            return None

    def _play_audio(self, audio_path):
        """Play an audio file using system command (non-blocking)."""
        if not audio_path or not os.path.exists(audio_path):
            print(f"Audio file not found: {audio_path}")
            return False

        # Stop any currently playing audio
        self._stop_audio()

        try:
            if sys.platform == "darwin":  # macOS
                self.audio_process = subprocess.Popen(
                    ["afplay", audio_path], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
                )
            elif sys.platform.startswith("linux"):
                # Try multiple Linux audio players
                for player in ["aplay", "play", "cvlc --play-and-exit", "ffplay -nodisp -autoexit"]:
                    if (
                        subprocess.run(
                            f"which {player.split()[0]}", shell=True, capture_output=True
                        ).returncode
                        == 0
                    ):
                        self.audio_process = subprocess.Popen(
                            f"{player} '{audio_path}'",
                            shell=True,
                            stdout=subprocess.DEVNULL,
                            stderr=subprocess.DEVNULL,
                        )
                        break
            elif sys.platform == "win32":  # Windows
                # For Windows, use PowerShell to play audio in a way we can control
                self.audio_process = subprocess.Popen(
                    [
                        "powershell",
                        "-c",
                        f"(New-Object Media.SoundPlayer '{audio_path}').PlaySync()",
                    ],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
            else:
                print(f"Unsupported platform for audio playback: {sys.platform}")
                return False
            return True
        except Exception as e:
            print(f"Error playing audio: {e}")
            return False

    def _stop_audio(self):
        """Stop currently playing audio."""
        if self.audio_process and self.audio_process.poll() is None:
            try:
                self.audio_process.terminate()
                # Give it a moment to terminate gracefully
                try:
                    self.audio_process.wait(timeout=1)
                except subprocess.TimeoutExpired:
                    # Force kill if it doesn't terminate gracefully
                    self.audio_process.kill()
                print("Audio stopped")
            except Exception as e:
                print(f"Error stopping audio: {e}")
            finally:
                self.audio_process = None

    def _get_labeling_summary(self):
        """Calculate and return labeling session summary."""
        labeled_count = sum(
            1 for c in self.candidates if c.get("needs_human_label", "").strip() != ""
        )
        unlabeled_count = len(self.candidates) - labeled_count
        total_count = len(self.candidates)

        return {
            "labeled": labeled_count,
            "unlabeled": unlabeled_count,
            "total": total_count,
            "percentage": (labeled_count / total_count * 100) if total_count > 0 else 0,
        }

    def _show_session_summary(self, summary):
        """Display labeling session summary."""
        print("\n" + "=" * 50)
        print("LABELING SESSION SUMMARY")
        print("=" * 50)
        print(f"Total samples: {summary['total']}")
        print(f"Labeled: {summary['labeled']} ({summary['percentage']:.1f}%)")
        print(f"Unlabeled: {summary['unlabeled']}")

    def _handle_quit_with_summary(self):
        """Handle quit command with session summary and confirmation."""
        self._stop_audio()

        # Show session summary
        summary = self._get_labeling_summary()
        self._show_session_summary(summary)

        # If there are unlabeled samples, ask for confirmation
        if summary["unlabeled"] > 0:
            print(f"\nYou have {summary['unlabeled']} unlabeled samples remaining.")
            print("Unlabeled samples will get new predictions in the next cycle.")
            confirm = input("Are you sure you want to quit? (y/n): ").strip().lower()
            if confirm not in ["y", "yes"]:
                print("Continuing labeling session...")
                return False  # Don't quit

        # Save if needed and exit
        if self.changes_made:
            save = input("\nSave changes before quitting? (y/n): ").strip().lower()
            if save in ["y", "yes"]:
                self._save_candidates()
                print("Labels saved!")

        print("Session complete. Goodbye!")
        return True  # Quit confirmed

    def _save_candidates(self):
        """Save candidates back to CSV file."""
        if not self.fieldnames:
            print("Error: No fieldnames available for CSV writing")
            return

        with open(self.candidates_csv, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=self.fieldnames)
            writer.writeheader()
            writer.writerows(self.candidates)
        self.changes_made = False
        print(f"\nSaved labels to {self.candidates_csv}")

    def _auto_play_current(self):
        """Auto-play current sample's audio."""
        if self.current_index < len(self.candidates):
            audio_path = self._get_audio_path(self.candidates[self.current_index])
            if audio_path:
                print("\nPlaying audio...")
                self._play_audio(audio_path)

    def _advance_and_play(self):
        """Advance to next sample and auto-play audio."""
        if self.current_index < len(self.candidates) - 1:
            self.current_index += 1
            self._display_current()
            self._auto_play_current()

    def _label_and_advance(self, label: str, message: str):
        """Label current sample and advance to next with auto-play."""
        if self.current_index < len(self.candidates):
            self.candidates[self.current_index]["needs_human_label"] = label
            self.changes_made = True
            print(f"✓ {message}")
            self._advance_and_play()

    def _jump_to_sample(self, index: int):
        """Jump to a specific sample and display it."""
        if 0 <= index < len(self.candidates):
            self.current_index = index
            self._display_current()
            return True
        return False

    def _display_current(self):
        """Display current candidate information."""
        if self.current_index >= len(self.candidates):
            print("\nNo more candidates to label!")
            return

        candidate = self.candidates[self.current_index]

        print("\n" + "=" * 60)
        print(
            f"Sample {self.current_index + 1} of {len(self.candidates)} ({self.dataset_name.upper()})"
        )
        print("=" * 60)

        # Display candidate info
        print(f"Filename: {candidate.get('filename', 'Unknown')}")
        print(f"Filepath: {candidate.get('filepath', 'Unknown')}")
        print(f"Prediction: {candidate.get('predicted_class', 'Unknown')}")
        print(f"Confidence: {candidate.get('confidence', 'Unknown')}")
        print(f"Original Class: {candidate.get('original_class', 'Unknown')}")

        current_label = candidate.get("needs_human_label", "").strip()
        if current_label:
            print(f"Current Label: {current_label}")
        else:
            print("Current Label: [Not yet labeled]")

        # Progress bar
        labeled = sum(1 for c in self.candidates if c.get("needs_human_label", "").strip() != "")
        progress = labeled / len(self.candidates) * 100
        bar_length = 40
        filled = int(bar_length * labeled / len(self.candidates))
        bar = "█" * filled + "░" * (bar_length - filled)
        print(f"\nProgress: [{bar}] {labeled}/{len(self.candidates)} ({progress:.1f}%)")

    def _show_help(self):
        """Display help information."""
        print("\nCommands:")
        print("  1      - Label as POSITIVE (1) - This IS the target sound")
        print("  0      - Label as NEGATIVE (0) - This is NOT the target sound")
        print("  n      - Next sample (without labeling)")
        print("  p      - Play/replay audio")
        print("  x      - Stop currently playing audio")
        print("  b      - Previous sample")
        print("  j      - Jump to sample number")
        print("  u      - Jump to next unlabeled (great for resuming)")
        print("  s      - Save progress (also auto-saves on quit)")
        print("  h or ? - Show this help")
        print("  q      - Quit (shows session summary and prompts to save)")
        print("\nTip: After labeling with 1/0, audio auto-plays for the next sample")
        print(
            "Note: When quitting, you'll see a summary and confirmation if samples remain unlabeled"
        )

    def run(self):
        """Run the interactive labeling session."""
        print(f"\nSimple Audio Labeling Tool - {self.dataset_name.upper()}")
        print("Type 'h' for help")
        print("Commands: 1=positive, 0=negative, u=next unlabeled, x=stop audio, q=quit")
        print(
            "Note: Quitting shows a session summary and asks for confirmation if samples remain unlabeled\n"
        )

        # Display first candidate and auto-play
        self._display_current()
        self._auto_play_current()

        try:
            while True:
                try:
                    command = input("\nCommand: ").strip().lower()

                    if not command:
                        continue

                    if command in ["q", "quit"]:
                        if self._handle_quit_with_summary():
                            break

                    elif command in ["h", "help", "?"]:
                        self._show_help()

                    elif command == "1":
                        self._label_and_advance("1", "Labeled as POSITIVE (1)")

                    elif command == "0":
                        self._label_and_advance("0", "Labeled as NEGATIVE (0)")

                    elif command == "p":
                        self._auto_play_current()
                        if not self._get_audio_path(self.candidates[self.current_index]):
                            print("ERROR: No valid audio file path found")

                    elif command == "x":
                        self._stop_audio()

                    elif command == "n":  # Next without labeling
                        if self.current_index < len(self.candidates) - 1:
                            self.current_index += 1
                            self._display_current()

                    elif command == "b":  # Back/previous
                        if self.current_index > 0:
                            self.current_index -= 1
                            self._display_current()

                    elif command == "j":
                        try:
                            jump_to = int(input("Jump to sample number (1-based): ")) - 1
                            if not self._jump_to_sample(jump_to):
                                print("Invalid sample number!")
                        except ValueError:
                            print("Invalid number!")

                    elif command == "u":
                        # Jump to next unlabeled
                        found = False
                        for i in range(self.current_index + 1, len(self.candidates)):
                            if self.candidates[i].get("needs_human_label", "").strip() == "":
                                self.current_index = i
                                found = True
                                break

                        if not found:
                            # Wrap around to beginning
                            for i in range(0, self.current_index):
                                if self.candidates[i].get("needs_human_label", "").strip() == "":
                                    self.current_index = i
                                    found = True
                                    break

                        if found:
                            self._display_current()
                            self._auto_play_current()
                        else:
                            print("No unlabeled samples found!")

                    elif command == "s":
                        self._save_candidates()

                    else:
                        print(f"Unknown command: '{command}'. Type 'h' for help.")

                except KeyboardInterrupt:
                    print("\n\nInterrupted!")
                    if self._handle_quit_with_summary():
                        break
        finally:
            # Ensure audio is stopped when exiting
            self._stop_audio()


def test_audio_playback(audio_file):
    """Test audio playback with a specific file."""
    print(f"\nTesting audio playback with: {audio_file}")

    if not os.path.exists(audio_file):
        print("File not found")
        return

    if sys.platform == "darwin":
        try:
            result = subprocess.run(["afplay", audio_file], capture_output=True, text=True)
            if result.returncode == 0:
                print("Audio playback successful")
            else:
                print(f"Audio playback failed: {result.stderr}")
        except Exception as e:
            print(f"Error: {e}")


def main():
    parser = argparse.ArgumentParser(
        description="Audio labeling tool for active learning with multi-dataset support",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Example workflows:

FSD50K (default):
  # Use default dataset (or set AUDIOLOOP_DATASET=fsd50k)
  python -m audioloop.label_audio outputs/labeling_candidates_v1.csv

  # Explicit dataset specification
  python -m audioloop.label_audio outputs/labeling_candidates_v1.csv --dataset fsd50k --audio-dir data/FSD50K/FSD50K.dev_audio

UrbanSound8K:
  # Set environment variable
  AUDIOLOOP_DATASET=urbansound8k python -m audioloop.label_audio outputs/labeling_candidates_v1.csv

  # Explicit dataset specification
  python -m audioloop.label_audio outputs/labeling_candidates_v1.csv --dataset urbansound8k --audio-dir data/urbansound8k

Full workflow example:
  # Run active learning to generate candidates
  python -m audioloop.active_learning --class-name dog_bark --run-number 1

  # Label the candidates (uses AUDIOLOOP_DATASET or default)
  python -m audioloop.label_audio outputs/labeling_candidates_v1.csv

  # Merge labels back into training set
  python -m audioloop.merge_labels training_sets/training_set_v1.csv outputs/labeling_candidates_v1.csv

Automated labeling (for testing):
  # For auto-labeling with ground truth (evaluation workflows), use:
  # python -m audioloop.auto_label_candidates outputs/labeling_candidates_v1.csv

Requirements:
  - Candidates CSV must come from active_learning.py (has 'filepath' column)
  - Audio files must be in proper dataset structure:
    * UrbanSound8K: fold1-fold10 directories
    * FSD50K: flat directory structure
  - For custom audio directories, use --audio-dir

Audio playback:
  - macOS: uses built-in afplay
  - Linux: install sox ('sudo apt-get install sox') for play command
  - Windows: uses default audio player

Dataset to use ('fsd50k' or 'urbansound8k'). Can also be set via AUDIOLOOP_DATASET environment variable.
        """,
    )

    parser.add_argument(
        "candidates_csv", help="Path to labeling candidates CSV from active learning"
    )

    # Dynamic dataset discovery
    from audioloop.datasets.dataset_registry import list_available_datasets

    available_datasets = list_available_datasets()

    parser.add_argument(
        "--dataset",
        choices=available_datasets,
        help=f"Dataset type. Available: {', '.join(available_datasets)}. Uses AUDIOLOOP_DATASET env var or default if not specified.",
    )

    parser.add_argument(
        "--audio-dir",
        help="Audio directory (uses dataset default if not specified)",
    )

    parser.add_argument(
        "--test-audio", help="Test audio playback with a specific file", metavar="FILE"
    )

    args = parser.parse_args()

    # Handle dataset resolution
    config = AudioLoopConfig.from_project(dataset=args.dataset)
    dataset_name = config.dataset

    # Handle test mode
    if args.test_audio:
        test_audio_playback(args.test_audio)
        return

    if not os.path.exists(args.candidates_csv):
        print(f"Error: Candidates file not found: {args.candidates_csv}")
        sys.exit(1)

    # Verify it's from active learning workflow
    with open(args.candidates_csv) as f:
        reader = csv.DictReader(f)
        first_row = next(reader, None)
        if first_row and "filepath" not in first_row:
            print("Error: This tool requires a candidates CSV from the active learning workflow.")
            print("The CSV must have a 'filepath' column.")
            print(f"Found columns: {list(first_row.keys())}")
            sys.exit(1)

    # Create labeler and run
    labeler = SimpleAudioLabeler(
        args.candidates_csv, dataset_name=dataset_name, audio_dir=args.audio_dir
    )

    try:
        labeler.run()
    except Exception as e:
        print(f"\nError: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
